//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class isler
    {
        public int id { get; set; }
        public string is_adi { get; set; }
        public System.DateTime olusturuldugu_tarih { get; set; }
        public string durum { get; set; }
        public Nullable<System.DateTime> tamamlandigi_tarih { get; set; }
    }
}
